word = input("")
from time import sleep


while True:
    print(""+ word +"")
    sleep(0.04)
    print(" "+ word +"")
    sleep(0.04)
    print("  "+ word +"")
    sleep(0.04)
    print("   "+ word +"")
    sleep(0.04)
    print("    "+ word +"")
    sleep(0.04)
    print("     "+ word +"")
    sleep(0.04)
    print("      "+ word +"")
    sleep(0.04)
    print("       "+ word +"")
    sleep(0.04)
    print("        "+ word +"")
    sleep(0.04)
    print("         "+ word +"")
    sleep(0.04)
    print("        "+ word +"")
    sleep(0.04)
    print("       "+ word +"")
    sleep(0.04)
    print("      "+ word +"")
    sleep(0.04)
    print("     "+ word +"")
    sleep(0.04)
    print("    "+ word +"")
    sleep(0.04)
    print("   "+ word +"")
    sleep(0.04)
    print("  "+ word +"")
    sleep(0.04)
    print(" "+ word +"")
    sleep(0.04)
    